spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/jewelrydb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Vishu@sql123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET:8f8303f25608d408eb19d425f1901a52e26922573f08f863e414c6e949cb24e8}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000} # 15 minutes
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
