spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/jewelry_order_test_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Vishu@sql123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

eureka:
  client:
    enabled: false

logging:
  level:
    com.jewelry.order: INFO
